### ISSUE TITLE
Unable to complete last two steps in detailed training notebook.

### ISSUE THREAD

**Issue by JigglesTheFett** [dscripka/openWakeWord#58] opened 2023-10-13 13:35 UTC
Hello! This is the error that I receive while attempting to complete the 'Train the Model' step #2

/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
INFO:root:##################################################
Computing openwakeword features for generated samples
##################################################
Traceback (most recent call last):
  File "/content/openwakeword/openwakeword/train.py", line 638, in <module>
    compute_features_from_generator(positive_clips_train_generator, n_total=len(os.listdir(positive_train_output_dir)),
  File "/content/openwakeword/openwakeword/utils.py", line 556, in compute_features_from_generator
    F = AudioFeatures(device=device)
  File "/content/openwakeword/openwakeword/utils.py", line 84, in __init__
    self.melspec_model = ort.InferenceSession(melspec_model_path, sess_options=sessionOptions,
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /content/openwakeword/openwakeword/resources/models/melspectrogram.onnx failed:Load model /content/openwakeword/openwakeword/resources/models/melspectrogram.onnx failed. File doesn't exist

And this happens on the next step immediately after:
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/content/openwakeword/openwakeword/train.py", line 666, in <module>
    F = openwakeword.utils.AudioFeatures(device='cpu')
  File "/content/openwakeword/openwakeword/utils.py", line 84, in __init__
    self.melspec_model = ort.InferenceSession(melspec_model_path, sess_options=sessionOptions,
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /content/openwakeword/openwakeword/resources/models/melspectrogram.onnx failed:Load model /content/openwakeword/openwakeword/resources/models/melspectrogram.onnx failed. File doesn't exist

**Comment by dscripka** [comment] 2023-10-13 13:56
This is likely the same bug that was reported in #55, which should be fixed now. In particular, in the first code cell of the Colab notebook it downloads these assets which are missing.

If you made a copy of the Colab notebook, you might need to make a new copy with the updated version.

**Comment by dscripka** [comment] 2023-10-13 20:02
@JigglesTheFett thank you for continuing to report issues, and apologies that the process hasn't been as smooth as intended! This seems to be an intermittent bug I've seen on Colab, so I've updated the notebook to include another cell with a function to convert the .onnx file to .tflite:

```python
# Manually save to tflite as this doesn't work right in colab
def convert_onnx_to_tflite(onnx_model_path, output_path):
    """Converts an ONNX version of an openwakeword model to the Tensorflow tflite format."""
    # imports
    import onnx
    import logging
    import tempfile
    from onnx_tf.backend import prepare
    import tensorflow as tf

    # Convert to tflite from onnx model
    onnx_model = onnx.load(onnx_model_path)
    tf_rep = prepare(onnx_model, device="CPU")
    with tempfile.TemporaryDirectory() as tmp_dir:
        tf_rep.export_graph(os.path.join(tmp_dir, "tf_model"))
        converter = tf.lite.TFLiteConverter.from_saved_model(os.path.join(tmp_dir, "tf_model"))
        tflite_model = converter.convert()

        logging.info(f"####\nSaving tflite mode to '{output_path}'")
        with open(output_path, 'wb') as f:
            f.write(tflite_model)

    return None
```

**Comment by JigglesTheFett** [comment] 2023-10-13 20:04
Amazing! Thanks so much, and no worries it on not being all that smooth, you've created something amazing here, so it's more than worth the slight amount of hassle.

**Closed** 2023-10-13 23:31 UTC
