### ISSUE TITLE
[HomeAssistant] OpenWakeWord has variable behaviour for multiple assistants

### ISSUE THREAD

**Issue by HarvsG** [dscripka/openWakeWord#61] opened 2023-10-16 11:06 UTC
Copied from https://github.com/home-assistant/addons/issues/3259

### Which add-on are you reporting an issue with?

OpenWakeWord

### What is the version of the add-on?

1.7.0

### Steps to reproduce the issue

1. Configure more than 1 voice assistant, with different wake words (I use a completely nabu-casa pipeline for 'hey rasspy' and a nabu casa/OpenAI ChatGPT for 'hey jarvis'. Set 'hey rasspy' to be your favourite.
2. Configure a home-assistant satellite
3. Make plenty of 'hey rasspy' commands and see them succeed, in the OpenWakeWord debug log see single entries of `DEBUG:root:Triggered hey_rhasspy_v0.1 (client=8641896508078)`
4. Switch the favourite to being jarvis - see in the debug log that OpenWakeWord loads the 'hey jarvis' model (and does not unload 'hey rhasspy'. See that 'hey jarvis' commands succeeed.
5. Switch the favourite back to the 'hey rasspy' assistant 
6. Make some 'hey jarvis' commands, from the `home-assistant satellite` command --debug feed see no acknowledgement of wake-work detection.
7. In the OpenWakeWork debug log see duplicate entries for wake word detection for the non-favourite voice assistant: 
```
DEBUG:root:Triggered hey_jarvis_v0.1 (client=8650962437429)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=8650962437429)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=8650962437429)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=8650962437429)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=8650962437429)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=8650962437429)
```
8. Switch which is the favourite (starred) voice assistant and see the behaviour reverse

Ok, after some digging, I can refine the behaviour.
If you restart OpenWakeWord it will only detect the wake-word of the currently favourited assistant.
If you switch favourite assistant whilst OpenWakeWord is running, it will load the new wake word. It will still detect the previous favourite (with the duplications in the debug log) but wyoming will skip/ignore the old favourite wake word.

So it seems multiple assistants are not supported in wyoming, and they can be supported in OpenWakeWord via this work-around of favourite-switching

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:150
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:09:12 PM (121 occurrences)
Last logged: 2:51:59 PM

[546757196992] Received binary message for non-existing handler 1
[546928783296] Received binary message for non-existing handler 1
[546739480256] Received binary message for non-existing handler 1
[546805007936] Received binary message for non-existing handler 1
[546805022272] Received binary message for non-existing handler 1
```

### Anything in the add-on logs that might be useful for us?

```txt
Logger: homeassistant.components.wyoming.wake_word
Source: components/wyoming/wake_word.py:123
Integration: Wyoming Protocol (documentation, issues)
First occurred: 2:53:34 PM (2 occurrences)
Last logged: 2:53:34 PM

Expected wake word hey_rhasspy_v0.1 but got hey_jarvis_v0.1, skipping
```

### OpenWakeWord log

```
DEBUG:root:Triggered hey_rhasspy_v0.1 (client=5826969686261)
DEBUG:wyoming_openwakeword.handler:Client disconnected: 5826969686261
DEBUG:wyoming_openwakeword.handler:Client connected: 5835970430964
DEBUG:wyoming_openwakeword.handler:Receiving audio from client: 5835970430964
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:root:Triggered hey_jarvis_v0.1 (client=5835970430964)
DEBUG:wyoming_openwakeword.handler:Client connected: 5855276917884
DEBUG:wyoming_openwakeword.handler:Sent info to client: 5855276917884
DEBUG:wyoming_openwakeword.handler:Client disconnected: 5855276917884
DEBUG:wyoming_openwakeword.handler:Client connected: 5887450564782
DEBUG:wyoming_openwakeword.handler:Sent info to client: 5887450564782
DEBUG:wyoming_openwakeword.handler:Client disconnected: 5887450564782
DEBUG:wyoming_openwakeword.handler:Client connected: 5919591716748
DEBUG:wyoming_openwakeword.handler:Sent info to client: 5919591716748
DEBUG:wyoming_openwakeword.handler:Client disconnected: 5919591716748
DEBUG:wyoming_openwakeword.handler:Client connected: 5951717174131
DEBUG:wyoming_openwakeword.handler:Sent info to client: 5951717174131
DEBUG:wyoming_openwakeword.handler:Client disconnected: 5951717174131
DEBUG:wyoming_openwakeword.handler:Client connected: 5983853725401
DEBUG:wyoming_openwakeword.handler:Sent info to client: 5983853725401
DEBUG:wyoming_openwakeword.handler:Client disconnected: 5983853725401
DEBUG:wyoming_openwakeword.handler:Client connected: 6016004259331
DEBUG:wyoming_openwakeword.handler:Sent info to client: 6016004259331
DEBUG:wyoming_openwakeword.handler:Client disconnected: 6016004259331
DEBUG:wyoming_openwakeword.handler:Client connected: 6048179180758
DEBUG:wyoming_openwakeword.handler:Sent info to client: 6048179180758
DEBUG:wyoming_openwakeword.handler:Client disconnected: 6048179180758
```

**Comment by HarvsG** [comment] 2023-10-16 11:10
Apologies if this issue should be kept to the HomeAssitant addon repo, it's hard for me to know where the issue lies. Please do close this if it is in the wrong place.

**Comment by dscripka** [comment] 2023-10-17 12:13
Looks like the issue is likely with Wyoming or another part of HomeAssistant addons, as openWakeWord seems to activate correctly with both wake words when you switch the order.

Closing this for now until there is more information from the other repos, but if it looks like the problem is indeed with openWakeWord feel free to re-open or create another issue.

**Closed by dscripka** 2023-10-17 12:13 UTC
